# TASK: apache log file analysis
# 1. How many unique IP addresses are connected to the proxy server?
# 2. How many unique domains were accessed by all workstations?
# 3. What status code is generated by the HTTP requests to the least accessed domain?
# 4. Based on the high count of connection attempts, what is the name of the suspicious domain? (hint: ending with .thm)
# 5. What is the source IP of the workstation that accessed the malicious domain?
